title: My title
author: daniyarmukhanov
email: mukhanov.daniyar+githubpages@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Android developer

# social links
twitter_username: daniyarmukhanov
github_username:  daniyarmukhanov

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
